### ISSUE TITLE
Cannot create property ID in class Something

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Simplified#1]
Project compiles but don't start if I create a property ID in class Something.cs.

The property:
```csharp
public string ID {
	get {
		return this.GetObjectID();
	}
}
```

The exception:
> Error	14	At least one error has been detected during weaving of the application code. Process exit code: 4050 (ScErrWeavingError (SCERR2030))

**Comment by miyconst** [comment]
Everything works fine if change property's name to Key.

**Comment by warpech** [comment]
Was there any additional error in Administrator -> Log?

**Comment by miyconst** [comment]
Yes, two of them:

**Comment by miyconst** [comment]
System.Exception: ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 4050
 Version: 2.0.3085.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.
 at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 138
 at Starcounter.Server.WeaverService.Weave(String givenAssembly, String runtimeDirectory) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 116
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass7.<Execute>b__3(CommandTask task) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 99
 at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass1.<WithinTask>b__0(CommandTask t) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 484
 at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 510
 at Starcounter.Server.Commands.StartExecutableCommandProcessor.Execute() in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 104
 at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 300
 HResult=-2146233088
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR2030
 ---> System.FormatException: ScErrWrongErrorMessageFormat (SCERR1033): Parsing an error message string failed due to an incorrect message format. Message: SCDCV06 - ScErrFieldRedeclaration (SCERR4050): A database class declared a persistent field that has already been declared in one of the parent classes. Version: 2.0.3085.3. Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4050. <,0,0>
 Version: 2.0.3085.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR1033.
 at Starcounter.Internal.ParsedErrorMessage.InternalParseMessage(String errorMessage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Starcounter.Internal\ErrorHandling\ParsedErrorMessage.cs:line 114
 at Starcounter.Internal.ParsedErrorMessage.Parse(String errorMessage) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Starcounter.Internal\ErrorHandling\ParsedErrorMessage.cs:line 65
 at Starcounter.Server.WeaverService.LogAndRaiseExceptionFromFailingWeaver(ToolInvocationException e) in c:\TeamCity\TeamCity8\buildAgent\work\sc-2.0.3085.3\Level1\src\Server\Starcounter.Server\CoreServices\WeaverService.cs:line 171
 HResult=-2146233033
 HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR1033

**Comment by miyconst** [comment]
ScErrWeavingError (SCERR2030): At least one error has been detected during weaving of the application code. Process exit code: 4050.
 Arguments=--maxerrors=1 --ErrorParcelId=A4A7D6FA-EB34-442A-B579-DBB1DBB859E3 Weave "E:\GitHub\People\bin\Debug\People.exe" --outdir="C:\Users\const\Documents\Starcounter\Personal\Temp\Default\Default-20150210T223255739\weaver\F0032F995E73924CB13228206A0788B6C608CDA3"
 Output:
 A4A7D6FA-EB34-442A-B579-DBB1DBB859E3SCDCV06 - ScErrFieldRedeclaration (SCERR4050): A database class declared a persistent field that has already been declared in one of the parent classes.
 Version: 2.0.3085.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4050. <,0,0>A4A7D6FA-EB34-442A-B579-DBB1DBB859E3
 SCDCV06 - ScErrFieldRedeclaration (SCERR4050): A database class declared a persistent field that has already been declared in one of the parent classes.
 Version: 2.0.3085.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4050. <,0,0>
 
 Version: 2.0.3085.3.
 Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR2030.

**Comment by dan31** [comment]
@per-samuelsson, @k-rus, do we reserve property named "ID" somewhere in Starcounter?

**Comment by k-rus** [comment]
`__id` is reserved. I don't remember that `ID` was reserved in the parts that I deal with.
The above error is from weaver, so the question is to @per-samuelsson, but I guess he has no access to the repository and might not be able to see the issue or be notified.

**Comment by warpech** [comment]
Mind that currently Simplified is using `Key`:

```c#
        public string Key {
            get {
                return this.GetObjectID();
            }
        }
```

But I guess the problem remains for `ID`

**Comment by per-samuelsson** [comment]
I don't remember either that we have reserved ID. I will do some preliminary tests and review the code a little, and get back after that.

**Comment by per-samuelsson** [comment]
I did a simple test, but on branch **next** (b/c I'm currently working on that, and it's bit of a hazzle to change). The following class weaved w/o a problem.

```C#
[Database] public class Test {
  public string ID {
    get { return ""; }
  }
}
```

That leads me to thinking two things: 1) either it's only on **develop** (which seems less likely), or 2) it might not be the ID in Something that actually fails, but that some other class extend Something and declare an ID field (that clash when you introduce it in Something).

Is (2) possible do you think?

(And yes, I know, the error reporting is really crappy in this case - sorry)

**Comment by per-samuelsson** [comment]
> Is (2) possible do you think?

Ring3.Product.ID

**Comment by warpech** [comment]
Good find! But then we have another problem - an unuseful error message.

**Comment by per-samuelsson** [comment]
> But then we have another problem - an unuseful error message.

Yep. Its the propagation between components that does not work properly. I know I have a similar issue on me in Starcounter repo. I'll take this one on as well.

**Comment by per-samuelsson** [comment]
> I know I have a similar issue on me in Starcounter repo.

https://github.com/Starcounter/Starcounter/issues/2629

Not the same, but related.

**Comment by per-samuelsson** [comment]
@warpech 

Seems I can not assign my self to this issue? Can you either put a similar one in Starcounter issue tracker, and reference this. Or, if you want to use the issue tracker here, somehow assign me? Thanks.

**Comment by warpech** [comment]
Created the error in Starcounter (linked above). Now you can assign yourself. Closing this.
